# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"mkdir_if_needed": "00_core.ipynb",
         "meta_to_img_path": "00_core.ipynb",
         "meta_to_mask_path": "00_core.ipynb",
         "fix_abangle": "00_core.ipynb",
         "meta_to_df": "00_core.ipynb",
         "draw_ellipse": "00_core.ipynb",
         "ellipse_to_bbox": "00_core.ipynb",
         "ring_float_to_class_int": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://drscotthawley.github.io/espiownage/"

git_url = "https://github.com/drscotthawley/espiownage/tree/master/"

def custom_doc_links(name): return None
